#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#82AAFF'

bspc rule -a discord desktop='4'
bspc rule -a firefoxdeveloperedition desktop='3'

pgrep -x Discord > /dev/null || discord &
pgrep -x firefox > /dev/null || firefox-developer-edition &
