#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config focused_border_color '#82AAFF'

bspc rule -a zoom desktop='2'
bspc rule -a firefoxdeveloperedition desktop='3'
bspc rule -a discord desktop='4'
bspc rule -a Pulseeffects desktop='9'
bspc rule -a Pavucontrol desktop='9'

pgrep -x DiscordDevelopm > /dev/null || discord-development &
pgrep -x firefox > /dev/null || firefox-developer-edition &
pgrep -x pulseeffects > /dev/null || pulseeffects &
pgrep -x pavucontrol > /dev/null || pavucontrol &

sleep 10

bspc rule -r firefoxdeveloperedition
bspc rule -r discord
bspc rule -r Pulseeffects
bspc rule -r Pavucontrol
